sudo: required
services:
  - docker

script:
  - docker run sohan0077/docker-multi-test npm test -- --coverage

after_success:
  - docker build -t sohan0077/docker-multi-client ./client
  - docker build -t sohan0077/docker-multi-server ./server
  - docker build -t sohan0077/docker-multi-worker ./worker
  - docker build -t sohan0077/docker-multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sohan0077/docker-multi-client
  - docker push sohan0077/docker-multi-server
  - docker push sohan0077/docker-multi-worker
  - docker push sohan0077/docker-multi-nginx
